import { SpritesheetData } from './types';

/**
 * Frame descriptors for `public/assets/ae-characters.png` (generated by
 * `scripts/gen_characters.py` — regenerate the sheet there, not by hand).
 *
 * The upstream AI Town descriptors (`f1`–`f8`) were emitted by a texture packer, so each
 * was sixty lines of literal coordinates. Ours is one regular grid, so it is built from
 * the layout instead: four character blocks laid out left to right, each 3 walk frames
 * across by 4 directions down.
 */

const FRAME = 32;
const FRAMES_PER_DIR = 3;
const BLOCK_W = FRAME * FRAMES_PER_DIR;

// Row order within a block, top to bottom.
const DIRECTIONS = ['down', 'left', 'right', 'up'] as const;

function blockAt(blockIndex: number): SpritesheetData {
  const frames: SpritesheetData['frames'] = {};
  DIRECTIONS.forEach((direction, row) => {
    for (let f = 0; f < FRAMES_PER_DIR; f++) {
      // Frame keys are `down`, `down2`, `down3` — the naming the animations map expects.
      const key = f === 0 ? direction : `${direction}${f + 1}`;
      frames[key] = {
        frame: { x: blockIndex * BLOCK_W + f * FRAME, y: row * FRAME, w: FRAME, h: FRAME },
        sourceSize: { w: FRAME, h: FRAME },
        spriteSourceSize: { x: 0, y: 0 },
      };
    }
  });
  return {
    frames,
    meta: { scale: '1' },
    animations: {
      down: ['down', 'down2', 'down3'],
      left: ['left', 'left2', 'left3'],
      right: ['right', 'right2', 'right3'],
      up: ['up', 'up2', 'up3'],
    },
  };
}

// Block order must match ORDER in scripts/gen_characters.py.
export const ray = blockAt(0);
export const kelly = blockAt(1);
export const sam = blockAt(2);
export const clinician = blockAt(3);
