import { Sprite } from '@pixi/react';
import * as PIXI from 'pixi.js';
import { backWall } from '../../data/aeBay';

/**
 * The back wall's tall front face, generated by scripts/gen_backwall.py.
 *
 * PixiStaticMap draws the tilemap as a flat grid — every cell is exactly one tile square,
 * with no notion of height (src/components/PixiStaticMap.tsx builds each sprite from a
 * fixed tileDim x tileDim texture rectangle). That is why the room reads as top-down
 * rather than 3/4: a wall can only ever be as tall as the row it occupies.
 *
 * This sidesteps that by not being a tile at all — it is one image positioned in raw
 * pixels (`backWall.x/y/w/h`, from data/aeBay.js), taller than its row on purpose, drawn
 * after the floor but before any character so it occludes correctly without needing
 * per-row y-sorting: nothing can ever stand behind it, because the tiles it overlaps
 * (the back wall row itself, and the last few pixels of the floor row in front of it)
 * are not walkable.
 */
export function BackWall() {
  const texture = PIXI.Texture.from(backWall.url, { resourceOptions: { scaleMode: PIXI.SCALE_MODES.NEAREST } });
  return (
    <Sprite
      texture={texture}
      x={backWall.x}
      y={backWall.y}
      width={backWall.w}
      height={backWall.h}
    />
  );
}
