#!/usr/bin/env python3
"""
Generate data/aeBay.js — the A&E Bay 3 map.

The previous map tiled a single blue floor tile across three identical rectangles with a
striped fill standing in for curtains, which read as a placeholder rather than a room.
This composes one bay deliberately: a back wall carrying the monitor, oxygen outlet and
gel dispenser, a trolley bed under the monitor, a cubicle curtain closing the bay off to
one side, and the clutter a real bay has around its edges.

Layout constraint: the walkable core x6-12, y5-11 must stay clear, because Bay 3's spawn
and idle-wander bounds are hardcoded to it (convex/aiTown/agentOperations.ts,
convex/aiTown/player.ts). Props are placed outside that box; the bed sits inside it but
goes in a background layer, so it draws under the characters and Ray can lie on it.

Run:  python3 scripts/gen_tileset.py && python3 scripts/gen_map.py
"""

import json

W, H = 64, 48
TD = 32
EMPTY = -1

T = json.load(open('data/tileIds.json'))

# Room bounds. The camera sits on the middle of this at ~2x, so everything that matters
# is inside it.
X0, X1 = 4, 14          # interior spans X0+1 .. X1-1
WALL_TOP_Y = 3          # upper wall row
WALL_Y = 4              # lower wall row, meets the floor
Y0, Y1 = 5, 11          # interior floor rows


def grid(fill):
    # Layers are indexed [x][y], matching the format the engine already expects.
    return [[fill for _ in range(H)] for _ in range(W)]


def put(layer, x, y, tile):
    if 0 <= x < W and 0 <= y < H:
        layer[x][y] = tile


# ---------------------------------------------------------------- background
# Layer 0: floor everywhere, so panning out shows more ward rather than void.
floor = grid(T['floor_a'])
for x in range(W):
    for y in range(H):
        # A little variation, deterministic so the map is stable between runs.
        n = (x * 7 + y * 13) % 11
        if n == 0:
            floor[x][y] = T['floor_b']
        elif n == 4:
            floor[x][y] = T['floor_c']
        elif n == 8:
            floor[x][y] = T['floor_scuff']

# Ambient occlusion where the back wall meets the floor. Without it the wall looks like a
# sticker laid on the floor rather than something standing up from it.
for x in range(X0, X1 + 1):
    floor[x][Y0] = T['floor_ao']

# Layer 1: walkable decor drawn under the characters — the bed, so Ray lies on it.
decor = grid(EMPTY)
BED_X, BED_Y = 8, 5
for row, (lt, rt) in enumerate([('bed_hl', 'bed_hr'), ('bed_ml', 'bed_mr'), ('bed_fl', 'bed_fr')]):
    put(decor, BED_X, BED_Y + row, T[lt])
    put(decor, BED_X + 1, BED_Y + row, T[rt])

# ---------------------------------------------------------------- objects
# Layer 0: structure. Anything here blocks movement.
walls = grid(EMPTY)
for x in range(X0, X1 + 1):
    put(walls, x, WALL_TOP_Y, T['wall_upper'])
    put(walls, x, WALL_Y, T['wall_lower'])

# Fittings set into the back wall, above the bed.
put(walls, BED_X + 1, WALL_Y, T['monitor'])
put(walls, BED_X, WALL_Y, T['oxygen'])
put(walls, 6, WALL_Y, T['gel'])
put(walls, 5, WALL_TOP_Y, T['clock'])
put(walls, 11, WALL_TOP_Y, T['ceiling_light'])

# Door through the back wall on the left.
put(walls, X0, WALL_Y, T['door_l'])
put(walls, X0 + 1, WALL_Y, T['door_r'])

# Left wall, and the cubicle curtain closing the bay on the right.
for y in range(Y0, Y1 + 1):
    put(walls, X0, y, T['wall_side_l'])
CURTAIN_X = 13
put(walls, CURTAIN_X, WALL_Y, T['curtain_rail'])
for i, y in enumerate(range(Y0, Y1)):
    put(walls, CURTAIN_X, y, T['curtain_a'] if i % 2 == 0 else T['curtain_b'])
put(walls, CURTAIN_X, Y1, T['curtain_hem'])

# Layer 1: loose equipment. A few of these sit inside the walkable box so they can be
# where they clinically belong — right against the bed — rather than pushed to the walls.
# Player.join and wanderDestination both retry on a blocked tile, so a handful of
# occupied squares inside the box costs nothing.
props = grid(EMPTY)
put(props, BED_X - 1, Y0, T['iv_top'])          # drip stand at the bed head
put(props, BED_X - 1, Y0 + 1, T['iv_bot'])
put(props, BED_X + 2, Y0, T['cabinet'])         # locker on the far side of the bed
put(props, BED_X + 3, Y0 + 2, T['chair'])       # Kelly's chair, pulled up to the bed
put(props, 6, Y0 + 3, T['stool'])
put(props, 12, Y0 + 4, T['trolley_top'])
put(props, 12, Y0 + 5, T['trolley_bot'])
put(props, 5, Y0, T['sink'])
put(props, 5, Y0 + 1, T['sharps'])
put(props, 5, Y0 + 5, T['waste'])

out = f"""// VeriSim A&E Bay 3 ward map — GENERATED by scripts/gen_map.py, do not edit by hand.
// Tileset: public/assets/ae-bay-tileset-v2.png, generated by scripts/gen_tileset.py.
//
// The walkable core x6-12, y5-11 is kept clear of blocking props because Bay 3's spawn
// and wander bounds are hardcoded to it (convex/aiTown/agentOperations.ts and
// convex/aiTown/player.ts). The bed is in a background layer rather than an object layer,
// so it draws under the characters instead of blocking them.

export const tilesetpath = "/ai-town/assets/ae-bay-tileset-v2.png"
export const tiledim = {TD}
export const screenxtiles = {W}
export const screenytiles = {H}
export const tilesetpxw = 256
export const tilesetpxh = 160

export const bgtiles = {json.dumps([floor, decor])}
export const objmap = {json.dumps([walls, props])}
export const animatedsprites = []

export const mapwidth = bgtiles[0].length
export const mapheight = bgtiles[0][0].length
"""
open('data/aeBay.js', 'w').write(out)
print(f'wrote data/aeBay.js  {W}x{H}')
